"""add docker container name to services

Revision ID: 21df012e4318
Revises: 3320e7482939
Create Date: 2026-09-05 14:21:14.928258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21df012e4318'
down_revision: Union[str, Sequence[str], None] = '3320e7482939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('docker_container_name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'docker_container_name')
    # ### end Alembic commands ###
